GET http://localhost:5000/api-key HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyNTgxOTkwNywiZXhwIjoxNzI1ODIzNTA3fQ.sw4q55OBzPPnLZeRvzgYttDvrGqBbERkV2-Vy093Wl4
