POST http://localhost:5000/monitor HTTP/1.1
Content-Type: application/json
x-api-key: 6f0b821d24a73054739b8e23506643f256398b25a358ac207f6bbd96bb7ae4bc


{
	"monitor": [
		{
			"attributeCode": "VOLT",
			"value": 12
		},
		{
			"attributeCode": "CURR",
			"value": 3
		},
		{
			"attributeCode": "POW",
			"value": 3
		},
		{
			"attributeCode": "TEMP",
			"value": 40
		},
		{
			"attributeCode": "LUM",
			"value": 90
		}
	]
}