# POST https://pju-api-production.up.railway.app/data/all HTTP/1.1
# Content-Type: application/json

# {
#     "sensor": [
#       { "sensorCode": "TEMP", "value": 35.0 },    
#       { "sensorCode": "HUM", "value": 34.5 },     
#       { "sensorCode": "SOLAR", "value": 800.0 },  
#       { "sensorCode": "RAIN", "value": 12.3 },    
#       { "sensorCode": "WATER", "value": 1.5 },    
#       { "sensorCode": "WINDSPD", "value": 5.5 },  
#       { "sensorCode": "WINDDIR", "value": 90.0 }, 
#       { "sensorCode": "CO", "value": 0.9 },       
#       { "sensorCode": "NO2", "value": 0.03 },     
#       { "sensorCode": "O3", "value": 0.05 },      
#       { "sensorCode": "PM", "value": 25.0 }       

#     ],
#     "pju" : {
#       "lamp": {
#         "brightness": 80,
#         "on" : false,
#         "isPJU": true
#       }, 
#       "monitor" : [ 
#         { "attributeCode" : "VOLT", "value" : 12.0  },
#         { "attributeCode" : "CURR", "value" : 20.3  },
#         { "attributeCode" : "POW", "value" : 5.0  }
#       ]

#     }
# }